# Generated by Django 3.1.3 on 2021-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.IntegerField(null=True),
        ),
    ]
