# Generated by Django 3.1.3 on 2021-04-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
